### ISSUE TITLE
Empty page shown on http://127.0.0.1:8096

### ISSUE THREAD

**Issue by petre-c** [Blockstream/blind_pin_server#24]
I followed the official guides on the [support article on Blockstream's help portal](https://help.blockstream.com/hc/en-us/articles/12800132096793-Set-up-a-personal-blind-oracle) as well as on this repo and on [that for Jade](https://github.com/Blockstream/Jade) and managed to set up and launch the pinserver on Windows.

pinserver is started at http://127.0.0.1:8069 but I am seeing an empty page if I open http://127.0.0.1:8069 in a browser.
I am expecting a similar browser-based workflow as the one officially supported through [the official website](https://jadefw.blockstream.com/pinqr/qrpin.html).

This is the docker log:

```cmd
C:\Users\Ptr\Repos\blind_pin_server>docker run -v ./server_private_key.key:/server_private_key.key -v ./pinsdir:/pins -p 8096:8096 --name tmpr dockerized_pinserver
run-parts: failed to open directory /etc/run_once: No such file or directory
Started runsvdir, PID is 9
wait for processes to start....
[uWSGI] getting INI configuration from /pinserver/wsgi.ini
*** Starting uWSGI 2.0.19.1-debian (64bit) on [Sun Oct  8 12:39:43 2023] ***
compiled with version: 10.2.1 20210110 on 11 June 2021 09:08:33
os: Linux-5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023
nodename: dbc717a6c5a9
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /etc/runit/runsvdir/default/wsgi
detected binary path: /usr/bin/uwsgi-core
setgid() to 33
setuid() to 33
chdir() to /
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /tmp/uwsgi.socket fd 3
Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x5566109c4590
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145872 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
added /usr/lib/python3.7 to pythonpath.
added /usr/local/lib/python3.7/dist-packages to pythonpath.
Using filesystem based storage
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x5566109c4590 pid: 13 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 13)
spawned uWSGI worker 1 (pid: 23, cores: 1)
[pid: 23|app: 0|req: 1/1] 172.17.0.1 () {58 vars in 1725 bytes} [Sun Oct  8 12:39:45 2023] GET / => generated 0 bytes in 3 msecs (HTTP/1.1 200) 2 headers in 78 bytes (1 switches on core 0)
[pid: 23|app: 0|req: 2/2] 172.17.0.1 () {58 vars in 1725 bytes} [Sun Oct  8 12:39:48 2023] GET / => generated 0 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 78 bytes (1 switches on core 0)
run: nginx: (pid 14) 5s
run: wsgi: (pid 13) 5s
```

Also had to add schema to the pinserver url in the Jade hardware wallet since the python script didn't accept the url without it
```python
--set-url https://127.0.0.1:8069
```
127.0.0.1:8096/index.html returns a Welcome to nginx! page
<img width="241" alt="image" src="https://github.com/Blockstream/blind_pin_server/assets/15320885/b1e5a61c-b944-462f-8da0-94524fe3844e">

Please provide instructions on how to execute the QR workflow using the personal pinserver.

Thank you!

**Comment by petre-c** [comment]
https://github.com/Blockstream/blind_pin_server/issues/16

**Comment by JamieDriver** [comment]
This server is a backend component with endpoints '/start_handshake', '/set_pin' and '/get_pin' - all which must be POSTed to.  There is no 'web server' functionality here to eg. use QR codes.

I believe a basic webserver is included in this repo: https://github.com/Blockstream/esp32_bc-ur/tree/emscripten - but it isn't really documented ...

**Comment by petre-c** [comment]
Thank you
